<a href="https://colab.research.google.com/github/ashishgeorge1811/naturallanguage/blob/master/wordembedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
### sentences

sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [0]:
#Initialize vocabulary size

vocabulary_size = 10000

In [0]:
#one hot representation

from tensorflow.keras.preprocessing.text import one_hot
onehot = [one_hot(words,vocabulary_size)for words in sent ]
print(onehot[0])

print(onehot)


[5347, 3462, 4307, 3829]
[[5347, 3462, 4307, 3829], [5347, 3462, 4307, 4917], [5347, 9615, 4307, 6877], [9444, 6166, 4843, 8450, 2959], [9444, 6166, 4843, 8450, 1027], [7401, 5347, 5699, 4307, 454], [2207, 497, 8690, 8450]]


In [0]:
#Word Embedding

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [0]:
import numpy as np

In [0]:
sentence_length = 8
embedding_docs = pad_sequences(onehot,padding='pre',maxlen=sentence_length) #in the 'post' it will add zeros after the docs
#print(embedding_docs[0])
print(embedding_docs)

[[   0    0    0    0 5347 3462 4307 3829]
 [   0    0    0    0 5347 3462 4307 4917]
 [   0    0    0    0 5347 9615 4307 6877]
 [   0    0    0 9444 6166 4843 8450 2959]
 [   0    0    0 9444 6166 4843 8450 1027]
 [   0    0    0 7401 5347 5699 4307  454]
 [   0    0    0    0 2207  497 8690 8450]]


In [0]:
dim = 10

In [0]:
model = Sequential()
model.add(Embedding(vocabulary_size,10,input_length=sentence_length))
model.compile('adam','mse')

In [0]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [0]:
print(model.predict(embedding_docs))

[[[ 4.13979925e-02 -4.61672544e-02 -4.81909625e-02  1.50392689e-02
    1.00803971e-02 -8.74859095e-03  3.59836966e-03 -1.99235324e-02
    2.28936113e-02 -4.57983501e-02]
  [ 4.13979925e-02 -4.61672544e-02 -4.81909625e-02  1.50392689e-02
    1.00803971e-02 -8.74859095e-03  3.59836966e-03 -1.99235324e-02
    2.28936113e-02 -4.57983501e-02]
  [ 4.13979925e-02 -4.61672544e-02 -4.81909625e-02  1.50392689e-02
    1.00803971e-02 -8.74859095e-03  3.59836966e-03 -1.99235324e-02
    2.28936113e-02 -4.57983501e-02]
  [ 4.13979925e-02 -4.61672544e-02 -4.81909625e-02  1.50392689e-02
    1.00803971e-02 -8.74859095e-03  3.59836966e-03 -1.99235324e-02
    2.28936113e-02 -4.57983501e-02]
  [ 1.66910402e-02 -2.80265883e-03 -2.52147205e-02 -2.55455263e-02
   -1.88000556e-02  1.47648565e-02  3.61181423e-03 -3.41194868e-02
    1.42500512e-02  2.87489183e-02]
  [ 3.65812667e-02 -1.76752731e-03  3.57966684e-02  1.95142739e-02
   -1.59170739e-02 -1.50310993e-02 -8.19861889e-04 -1.96978208e-02
   -3.42185423e-

In [0]:
print(embedding_docs[0])

[   0    0    0    0 5347 3462 4307 3829]


In [0]:
print(model.predict(embedding_docs)[0])

[[ 0.04139799 -0.04616725 -0.04819096  0.01503927  0.0100804  -0.00874859
   0.00359837 -0.01992353  0.02289361 -0.04579835]
 [ 0.04139799 -0.04616725 -0.04819096  0.01503927  0.0100804  -0.00874859
   0.00359837 -0.01992353  0.02289361 -0.04579835]
 [ 0.04139799 -0.04616725 -0.04819096  0.01503927  0.0100804  -0.00874859
   0.00359837 -0.01992353  0.02289361 -0.04579835]
 [ 0.04139799 -0.04616725 -0.04819096  0.01503927  0.0100804  -0.00874859
   0.00359837 -0.01992353  0.02289361 -0.04579835]
 [ 0.01669104 -0.00280266 -0.02521472 -0.02554553 -0.01880006  0.01476486
   0.00361181 -0.03411949  0.01425005  0.02874892]
 [ 0.03658127 -0.00176753  0.03579667  0.01951427 -0.01591707 -0.0150311
  -0.00081986 -0.01969782 -0.00342185 -0.04126458]
 [-0.00514255 -0.00741816  0.0428982  -0.02986981 -0.00157466  0.01912538
  -0.02672997 -0.00641732  0.01885797  0.04999099]
 [ 0.00368239  0.01986679 -0.00182074 -0.01843952 -0.03030754 -0.03675878
   0.02348398 -0.04253957  0.03568752  0.0381056 ]]
